# Staging Environment - H2 Database
spring:
  application:
    name: payroll-staging
  
  # H2 Database (Staging)
  datasource:
    url: jdbc:h2:mem:stagingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration for H2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:rawang17@gmail.com}
    password: ${MAIL_PASSWORD:fswc bscf gnyb iewm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# API Documentation (Enabled for testing)
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# JWT Configuration - CONSISTENT WITH OTHER ENVIRONMENTS
security:
  jwt:
    secret: ${JWT_SECRET:5dab7a23fbbd1f3eccb5ef839ac89af5fb6f0f0f5cc832209d8d459b15e4e4d5}
    expiration: ${JWT_EXPIRATION:3600000}  # 1 hour

# Info logging
logging:
  level:
    com.example.payroll: INFO
    org.springframework.security: WARN

# Limited management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics