# Production Environment - AWS RDS PostgreSQL
spring:
  application:
    name: payroll-prod
  
  # AWS RDS PostgreSQL Database (Production)
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME:payroll_prod}
    username: ${DB_USERNAME:payroll_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
  
  # JPA Configuration for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}  # Allow override from environment
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25

  # Email Configuration (From environment variables)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# API Documentation (Enabled)
springdoc:
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
    path: /api-docs

# JWT Configuration - FIXED to use consistent secret
security:
  jwt:
    secret: ${JWT_SECRET:5dab7a23fbbd1f3eccb5ef839ac89af5fb6f0f0f5cc832209d8d459b15e4e4d5}
    expiration: ${JWT_EXPIRATION:1800000}  # 30 minutes

# Production logging - configurable
logging:
  level:
    com.example.payroll: ${LOGGING_LEVEL_COM_EXAMPLE_PAYROLL:WARN}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:ERROR}
    root: ERROR

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

# Production server settings
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  error:
    include-stacktrace: never